import type { StarHistory } from "./star-history.js";
import type { Report } from "./core.js";
import { activity, splitMerges, type DailyPoint } from "./analytics.js";
import { escapeHtml, glyph } from "./view.js";
import { CATEGORIES, type LeaderboardRow } from "./catalog.js";
function line(history: DailyPoint[]): string {
  const rows = history.filter((row): row is DailyPoint & { stars: number } => row.stars !== null);
  if (rows.length < 2) return '<p class="chart-warming">First reading saved. The stars get a storyline after the next daily snapshot.</p>';
  const min = Math.min(...rows.map(row => row.stars)), max = Math.max(...rows.map(row => row.stars)), span = Math.max(1, max - min);
  const points = rows.map((row, index) => `${20 + index / (rows.length - 1) * 340},${130 - (row.stars - min) / span * 100}`).join(" ");
  return `<svg viewBox="0 0 380 160" role="img" aria-label="Stars across ${rows.length} daily snapshots"><path d="M20 135H360" stroke="var(--line)"/><polyline points="${points}" fill="none" stroke="var(--brand-green)" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/>${rows.map((row, index) => `<circle cx="${20 + index / (rows.length - 1) * 340}" cy="${130 - (row.stars - min) / span * 100}" r="4" fill="var(--brand-green)"><title>${row.day}: ${row.stars} stars</title></circle>`).join("")}</svg><p class="chart-caption">${rows[0].day} → ${rows.at(-1)!.day} · ${max.toLocaleString("en-US")} stars at the peak</p>`;
}
function starBars(history: StarHistory): string {
  const high = Math.max(1, ...history.days.map(row => row.added)), sum = history.days.reduce((total, row) => total + row.added, 0);
  return `<svg class="star-chart" viewBox="0 0 380 160" role="img" aria-label="${sum} stars added across ${history.days.length} days"><path d="M10 135H370" stroke="var(--line)"/>${history.days.map((row, index) => `<g tabindex="0" role="button" aria-label="${row.day}: ${row.added} stars added" data-help-title="Stars added" data-help="${row.day}: ${row.added.toLocaleString("en-US")} stars added. GitHub calendar boundaries apply."><rect x="${10 + index * 360 / history.days.length}" y="${135 - row.added / high * 110}" width="${Math.max(2, 360 / history.days.length - 3)}" height="${Math.max(1, row.added / high * 110)}" rx="2" fill="var(--brand-green)"/></g>`).join("")}<text x="10" y="155" fill="var(--muted)" font-size="11">${history.days[0].day.slice(5)}</text><text x="322" y="155" fill="var(--muted)" font-size="11">${history.days.at(-1)!.day.slice(5)}</text></svg><p class="chart-caption">+${sum.toLocaleString("en-US")} stars added · ${history.days.length} days</p>`;
}
export function chartsMarkup(report: Report, history: DailyPoint[] = [], baseline: LeaderboardRow[] = [], stars?: StarHistory | null): string {
  const split = splitMerges(report), total = split.humans + split.bots + split.unknown, fraction = total ? split.bots / total : 0, circumference = 2 * Math.PI * 52;
  const days = activity(report), max = Math.max(1, ...days.map(row => row.humans + row.bots + row.unknown));
  const bars = days.map((row, index) => { const h = row.humans / max * 100, b = row.bots / max * 100, u = row.unknown / max * 100, x = 12 + index * 25; return `<g><title>${row.day}: ${row.humans} human-account merges, ${row.bots} bot-account merges, ${row.unknown} unknown-account merges</title><rect x="${x}" y="${122 - h}" width="16" height="${h}" rx="3" fill="var(--brand-green)"/><rect x="${x}" y="${122 - h - b}" width="16" height="${b}" rx="3" fill="#AB69EB"/><rect x="${x}" y="${122 - h - b - u}" width="16" height="${u}" rx="3" fill="var(--line)"/></g>`; }).join("");
  const comparison = baseline, rank = comparison.findIndex(row => row.repository === report.repository), compared = comparison.slice(0, 5);
  const chartRows = [...compared]; if (rank >= 5) chartRows.push(comparison[rank]);
  const high = Math.max(1, ...chartRows.map(row => row.score));
  return `<div class="repo-charts">
    <section class="chart-panel"><h3>Humans vs. bots</h3><p>Who's keeping the merge button warm?</p><div class="bot-donut"><svg viewBox="0 0 140 140" role="img" aria-label="${split.humans} merges authored by human accounts; ${split.bots} by bot accounts"><circle cx="70" cy="70" r="52" fill="none" stroke="var(--line)" stroke-width="18"/><circle cx="70" cy="70" r="52" fill="none" stroke="var(--brand-green)" stroke-width="18" stroke-dasharray="${total ? split.humans / total * circumference : 0} ${circumference}" transform="rotate(-90 70 70)"/><circle cx="70" cy="70" r="52" fill="none" stroke="#AB69EB" stroke-width="18" stroke-dasharray="${fraction * circumference} ${circumference}" transform="rotate(${total ? -90 + split.humans / total * 360 : -90} 70 70)"/><text x="70" y="68" text-anchor="middle" fill="var(--ink)" font-size="26" font-weight="700">${Math.round(fraction * 100)}%</text><text x="70" y="88" text-anchor="middle" fill="var(--muted)" font-size="12">bot cameos</text></svg><div class="chart-legend"><span><i class="human-dot"></i>Human accounts <strong>${split.humans}</strong></span><span><i class="bot-dot"></i>Bot accounts <strong>${split.bots}</strong></span>${split.unknown ? `<span><i class="unknown-dot"></i>Unknown accounts <strong>${split.unknown}</strong></span>` : ""}</div></div><small>Based on GitHub's account type. This doesn't identify AI-written code.</small></section>
    <section class="chart-panel"><h3>The last 14 days</h3><p>Observed merges, with bots in purple.</p><svg class="activity-chart" viewBox="0 0 370 150" role="img" aria-label="Observed daily merges during the last 14 days"><path d="M8 124H360" stroke="var(--line)"/>${bars}<text x="12" y="145" fill="var(--muted)" font-size="11">${days[0].day.slice(5)}</text><text x="310" y="145" fill="var(--muted)" font-size="11">${days.at(-1)!.day.slice(5)}</text></svg><small>A sampled PR listing can miss merges. Green shows human accounts; purple shows bots.</small></section>
    <section class="chart-panel"><h3>${stars?.days.length ? "Stars this month" : "Stars over time"}</h3><p>${stars?.days.length ? "Stars added each day, from GitHub." : "Daily readings, starting from the first capture."}</p>${stars?.days.length ? starBars(stars) : line(history)}</section>
    <section class="chart-panel"><h3>In the same conversation</h3><p>${rank >= 0 ? `#${rank + 1} of ${comparison.length} compared snapshots in Comment Magnet.` : 'No review-comment winner in this snapshot yet.'}</p><div class="comparison-bars">${chartRows.map(row => `<div class="comparison-row${row.repository === report.repository ? " yours" : ""}"><span>${escapeHtml(row.repository)}</span><svg viewBox="0 0 100 12" preserveAspectRatio="none" aria-hidden="true"><rect width="${row.score / high * 100}" height="12" rx="6" fill="var(--brand-green)"/></svg><strong>${row.score}</strong></div>`).join("")}</div><a href="/leaderboards/comments">${CATEGORIES.comments.name} leaderboard ${glyph("arrow")}</a><small>Inline comments on one inspected PR. Each repo's read scope still applies.</small></section>
  </div>`;
}
